# Generated by Django 4.0.3 on 2022-05-19 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=10)),
                ('department', models.CharField(max_length=20)),
                ('student_number', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=11)),
            ],
        ),
    ]
